implement CI

diff --git a/.github/workflows/docker-images.yml b/.github/workflows/docker-images.yml
--- a/.github/workflows/docker-images.yml
+++ b/.github/workflows/docker-images.yml
@@ -13,7 +13,7 @@ env:
   CYAN: \033[1;36m
   BLANK: \033[0m
   WORKING_DIR: resources/multi-tools
-  IMAGE: multi-tools
+  IMAGE_NAME: multi-tools
   REPOSITORY: ixxel
 
 jobs:
@@ -32,7 +32,7 @@ jobs:
     - name: Lint with Hadolint
       id: lint-hadolint
       run: |
-        echo -e "${BLUE}[ STEP - LINTING DOCKERFILE ] > Linting ${IMAGE} Dockerfile with Hadolint.${BLANK}"
+        echo -e "${BLUE}[ STEP - LINTING DOCKERFILE ] > Linting ${IMAGE_NAME} Dockerfile with Hadolint.${BLANK}"
         echo -e "${CYAN}[ INFO ] > Hadolint version.${BLANK}"
         hadolint --version
         echo -e "${YELLOW}[ EXECUTING ] > Executing Dockerfile linting.${BLANK}"
@@ -57,6 +57,30 @@ jobs:
       run: |
         echo -e "${BLUE}[ STEP - BUILDING VERSION ] > Building docker image version.${BLANK}"
         echo -e "${YELLOW}[ EXECUTING ] > Executing building.${BLANK}"
-        VERSION=$(cat resources/multi-tools/Dockerfile | grep -oE "IMG_VERSION=\"[0-9.]+\"" | grep -oE "[0-9.]+")
+        VERSION=$(cat ${WORKING_DIR}/Dockerfile | grep -oE "IMG_VERSION=\"[0-9.]+\"" | grep -oE "[0-9.]+")
         IMAGE_VERSION=${VERSION}-${{ github.run_number }}
-        echo -e "${CYAN}[ INFO ] > Image version for ${IMAGE} is ${IMAGE_VERSION}.${BLANK}"
+        echo ::set-output name=IMAGE_VERSION::${IMAGE_VERSION}
+        echo -e "${CYAN}[ INFO ] > Image version for ${IMAGE_NAME} is ${IMAGE_VERSION}.${BLANK}"
+    - name: Build image with buildah
+      id: build-image
+      env:
+        APP_VERSION: ${{ steps.build-version.outputs.IMAGE_VERSION }}
+      run: |
+        echo -e "${BLUE}[ STEP - BUILDING IMAGE ] > Building docker image with buildah.${BLANK}"
+        echo -e "${CYAN}[ INFO ] > Buildah version.${BLANK}"
+        buildah --version
+        echo -e "${CYAN}[ INFO ] > Podman version.${BLANK}"
+        podman --version
+        echo -e "${YELLOW}[ EXECUTING ] > Executing build ${IMAGE_VERSION}.${BLANK}"
+        buildah bud -t ${IMAGE_NAME}:${IMAGE_VERSION} ${WORKING_DIR}
+        echo -e "${CYAN}[ INFO ] > Displaying podman built images.${BLANK}"
+        podman images
+        echo -e "${YELLOW}[ EXECUTING ] > Checking docker image execution.${BLANK}"
+        podman run --rm ${IMAGE_NAME}:${IMAGE_VERSION} cat /etc/os-release
+        if [[ $? = 0 ]]
+        then
+          echo -e "${GREEN}[ CHECK SUCCESS ] > Docker image working properly.${BLANK}"
+        else
+          echo -e "${RED}[ CHECK FAILED ] > Something wrong with docker image.${BLANK}"
+          exit 1
+        fi
